name: Compile firmware for Živý obraz service

on: [push, pull_request]

jobs:
  build-project:
    name: Compile firmware binaries for Zivy obraz
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Compile firmware binaries
        run: pio run
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          path: .pio/build/*/*.bin
          name: firmware
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    needs: build-project
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: firmware
        path: ${{ github.workspace }}
    - name: Create Release With Asset
      id: Release-AIO
      uses: Hs1r1us/Release-AIO@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{github.run_number}}
        asset_files: /home/runner/work/zivyobraz-fw/zivyobraz-fw/